version: '3.8'

services:
  backend:
    image: backend # replace with your backend Docker image name
    build: ./backend
    restart: unless-stopped
    env_file: ./backend/.env
    environment:
      - PORT = ${PORT}  
      - MONGODB_URI = ${MONGODB_URI}
    ports:
      - "9000:9000" # adjust port as needed
    networks:
      - mern-network # custom bridge network for communication

  client:
    image: client # replace with your client Docker image name
    build:
      context: ./client
    ports:
      - "3000:3000" # adjust port as needed
    networks:
      - mern-network # use the same network as backend for communication
    depends_on:
      - backend # ensures backend service is running before starting the client

networks:
  mern-network:
    driver: bridge
